### ISSUE TITLE
regularize degenerating compositional fields

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#293]
If you have no physical diffusion, the compositional field equation is degenerate where the velocity becomes zero.

we should try to set the total diffusion as something like
```
  diffusion = max(Ch^2, nu+nu_E)
```
but how do we pick C? Automatically?

**Comment by bangerth** [comment]
The units need to be correct, so there is likely a velocity appearing. One should take something like a reference velocity in surrounding cells or similar.

Alternative: average the artificial viscosity over neighboring cells. This should not be too hard now that we can ask cells for their `active_cell_index`:
1/ Compute the artificial viscosity also on ghost cells
2/ Average on every cell from itself and its immediate neighbors.

**Comment by tjhei** [comment]
> Alternative: average the artificial viscosity over neighboring cells

This won't work if you have a whole region where the velocity is zero. Is that a realistic problem? Not sure.

**Comment by bangerth** [comment]
I can see cases where the velocity is /small/ in a whole region but it shouldn't happen that it is zero.

**Comment by jdannberg** [comment]
The only case I can imagine is that once we have the advection only solver scheme, one could prescribe the velocity to zero in a whole region, but that's such a special case, I don't know if that's something we have to worry about now.

**Comment by bangerth** [comment]
We now have the ability to prescribe a velocity field. Could someone cook up an input file with which we can check different strategies?

**Comment by gassmoeller** [comment]
Now this is interesting. When I use the `advection only` solver scheme and prescribe a velocity of zero then there is no problem, even if the diffusion is zero (likely because in this case the timestep is fixed to `1 / temperature_degree` in `compute_time_step`).

In models like the ones in #282, where I start with an initial perturbation that then settles and everything becomes stationary though, the advection solver does not converge after about 25 timesteps, unless I add diffusion. Suspiciously both the models with constant composition, and constant temperature run smoothly as soon as I add diffusion to the temperature field. That is how I ended up investigating the time step size and found #745.

**Comment by bangerth** [comment]
Then I need to look at #745 before the release as well.

Does #745 fix the issue? If not, can you attach a testcase that shows the problem?

**Comment by bangerth** [comment]
(Ah, I see now that you say in #745 that it doesn't solve the problem...)

**Comment by gassmoeller** [comment]
Two examples (very similar, but one for temperature, one for composition) are here:
https://gist.github.com/gassmoeller/a13190166616cd86c08a

When looking at the rms velocity in these models there is a sudden jump in the second to last timestep (by a factor of 5), but that is the only strange thing. The last converging timestep looks ok, and then in both models the advection solver of the not constant field does not converge any more.

**Comment by gassmoeller** [comment]
Did you close this unintentionally? 
Although the case with an analytically prescribed velocity of zero seems to work, at least some cases where the velocity is nearly zero seem to crash (see my example prms). 
I am not feeling strongly about reopening this issue, also because I looked over this a while this morning and did not find a reasonable solution, and it is a very specific application that maybe never happens for real models. Still I think we should state something like a conclusion at the end of this issue.

Do we think the case where velocities are approaching zero (no convection any more) *and* the diffusion is zero (or the advection field is constant) is not a use case for ASPECT and it is therefore acceptable if the advection solver crashes from time to time in these models?

**Comment by bangerth** [comment]
I must have hit the "close" button instead of the "comment" button. I'll leave this open for now since I'd like to take a look eventually (whenever that will actually be).

**Comment by bangerth** [comment]
Some more discussion is in #851.

**Comment by yinghe616** [comment]
Yes, for the falling box example, the velocity is not zero, but comparable very small in the whole region...
